#this file indicates how codebuild must compile our code.
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # java version

  pre_build:
    commands:
      - echo "Verificando dependencias..."
      - chmod +x gradlew  # Asegura permisos de ejecución
      - ./gradlew dependencies  # Descarga dependencias

  build:
    commands:
      - echo "Construyendo la aplicación..."
      - ./gradlew clean jar  # Compila el código y genera el JAR
      - echo "Ejecutando pruebas..."
      - ./gradlew test  # Ejecuta pruebas unitarias

  post_build:
    commands:
      - echo "Build finalizado. Generando artefactos..."
      - cp build/libs/*.jar app.jar  # Copia el JAR final para su despliegue

artifacts:
  files:
    - app.jar
  discard-paths: yes

reports:
  test-reports:
    files:
      - build/test-results/test/*.xml
    base-directory: build/
    file-format: JUNITXML
# to allow putting logs on S3 is required setting bucket permissions as well as has a role on CodeBuild that can write on the bucket assigned.
#logs:
#  cloudWatchLogs:
#    status: ENABLED
#  s3Logs:
#    status: ENABLED
#    location: my-log-bucket/logs/
